/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
//[File]            : conn_host_csr_top.h
//[Revision time]   : Mon Dec 28 21:32:30 2020

#ifndef __CONN_HOST_CSR_TOP_REGS_H__
#define __CONN_HOST_CSR_TOP_REGS_H__

//****************************************************************************
//
//                     CONN_HOST_CSR_TOP CR Definitions
//
//****************************************************************************

#define CONN_HOST_CSR_TOP_BASE                                 (CONN_REG_CONN_HOST_CSR_TOP_ADDR)

#define CONN_HOST_CSR_TOP_BUS_MCU_STAT_ADDR                    (CONN_HOST_CSR_TOP_BASE + 0x0000) // 0000
#define CONN_HOST_CSR_TOP_CONN_INFRA_ON_BUS_TIMEOUT_IRQ_ADDR   (CONN_HOST_CSR_TOP_BASE + 0x014c) // 014C
#define CONN_HOST_CSR_TOP_CONN_INFRA_WAKEPU_TOP_ADDR           (CONN_HOST_CSR_TOP_BASE + 0x01a0) // 01A0
#define CONN_HOST_CSR_TOP_CONN2AP_REMAP_MCU_EMI_BASE_ADDR_ADDR (CONN_HOST_CSR_TOP_BASE + 0x01c4) // 01C4
#define CONN_HOST_CSR_TOP_CONN2AP_REMAP_MCU_1_EMI_BASE_ADDR_ADDR (CONN_HOST_CSR_TOP_BASE + 0x01c8) // 01C8
#define CONN_HOST_CSR_TOP_CONN2AP_REMAP_MD_SHARE_EMI_BASE_ADDR_ADDR (CONN_HOST_CSR_TOP_BASE + 0x01cc) // 01CC
#define CONN_HOST_CSR_TOP_CONN2AP_REMAP_GPS_EMI_BASE_ADDR_ADDR (CONN_HOST_CSR_TOP_BASE + 0x01d0) // 01D0
#define CONN_HOST_CSR_TOP_CONN2AP_REMAP_WF_PERI_BASE_ADDR_ADDR (CONN_HOST_CSR_TOP_BASE + 0x01d4) // 01D4
#define CONN_HOST_CSR_TOP_CONN2AP_REMAP_BT_PERI_BASE_ADDR_ADDR (CONN_HOST_CSR_TOP_BASE + 0x01d8) // 01D8
#define CONN_HOST_CSR_TOP_CONN2AP_REMAP_GPS_PERI_BASE_ADDR_ADDR (CONN_HOST_CSR_TOP_BASE + 0x01dc) // 01DC
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_ADDR     (CONN_HOST_CSR_TOP_BASE + 0x0380) // 0380
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_ADDR (CONN_HOST_CSR_TOP_BASE + 0x0384) // 0384
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_TIMER_ADDR       (CONN_HOST_CSR_TOP_BASE + 0x0388) // 0388
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_COUNTER_ADDR     (CONN_HOST_CSR_TOP_BASE + 0x038C) // 038C


/* =====================================================================================
  ---HOST_CONN_INFRA_SLP_CNT_CTL (0x18060000 + 0x0380)---
 =====================================================================================*/
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_HOST_SLP_COUNTER_CTL_EN_ADDR CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_ADDR
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_HOST_SLP_COUNTER_CTL_EN_MASK 0x80000000                // HOST_SLP_COUNTER_CTL_EN[31]
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_HOST_SLP_COUNTER_CTL_EN_SHFT 31
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_HOST_SLP_COUNTER_RD_TRIGGER_ADDR CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_ADDR
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_HOST_SLP_COUNTER_RD_TRIGGER_MASK 0x00000010                // HOST_SLP_COUNTER_RD_TRIGGER[4]
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_HOST_SLP_COUNTER_RD_TRIGGER_SHFT 4
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_HOST_SLP_COUNTER_SEL_ADDR CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_ADDR
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_HOST_SLP_COUNTER_SEL_MASK 0x0000000E                // HOST_SLP_COUNTER_SEL[3..1]
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_HOST_SLP_COUNTER_SEL_SHFT 1
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_HOST_SLP_COUNTER_EN_ADDR CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_ADDR
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_HOST_SLP_COUNTER_EN_MASK 0x00000001                // HOST_SLP_COUNTER_EN[0]
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_CTL_HOST_SLP_COUNTER_EN_SHFT 0

/* =====================================================================================
  ---HOST_CONN_INFRA_SLP_CNT_SLP_STOP (0x18060000 + 0x0384)---
 =====================================================================================*/
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_CONN_INFRA_IN_SLEEP_ADDR CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_ADDR
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_CONN_INFRA_IN_SLEEP_MASK 0x00800000                // HOST_CONN_INFRA_IN_SLEEP[23]
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_CONN_INFRA_IN_SLEEP_SHFT 23
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_BTSYS_IN_SLEEP_ADDR CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_ADDR
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_BTSYS_IN_SLEEP_MASK 0x00040000                // HOST_BTSYS_IN_SLEEP[18]
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_BTSYS_IN_SLEEP_SHFT 18
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_WFSYS_IN_SLEEP_ADDR CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_ADDR
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_WFSYS_IN_SLEEP_MASK 0x00020000                // HOST_WFSYS_IN_SLEEP[17]
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_WFSYS_IN_SLEEP_SHFT 17
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_GPSSYS_IN_SLEEP_ADDR CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_ADDR
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_GPSSYS_IN_SLEEP_MASK 0x00010000                // HOST_GPSSYS_IN_SLEEP[16]
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_GPSSYS_IN_SLEEP_SHFT 16
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_CONN_INFRA_SLP_COUNTER_CLR_ADDR CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_ADDR
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_CONN_INFRA_SLP_COUNTER_CLR_MASK 0x00008000                // HOST_CONN_INFRA_SLP_COUNTER_CLR[15]
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_CONN_INFRA_SLP_COUNTER_CLR_SHFT 15
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_BTSYS_SLP_COUNTER_CLR_ADDR CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_ADDR
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_BTSYS_SLP_COUNTER_CLR_MASK 0x00000400                // HOST_BTSYS_SLP_COUNTER_CLR[10]
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_BTSYS_SLP_COUNTER_CLR_SHFT 10
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_WFSYS_SLP_COUNTER_CLR_ADDR CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_ADDR
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_WFSYS_SLP_COUNTER_CLR_MASK 0x00000200                // HOST_WFSYS_SLP_COUNTER_CLR[9]
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_WFSYS_SLP_COUNTER_CLR_SHFT 9
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_GPSSYS_SLP_COUNTER_CLR_ADDR CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_ADDR
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_GPSSYS_SLP_COUNTER_CLR_MASK 0x00000100                // HOST_GPSSYS_SLP_COUNTER_CLR[8]
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_GPSSYS_SLP_COUNTER_CLR_SHFT 8
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_CONN_INFRA_SLP_COUNTER_STOP_ADDR CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_ADDR
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_CONN_INFRA_SLP_COUNTER_STOP_MASK 0x00000080                // HOST_CONN_INFRA_SLP_COUNTER_STOP[7]
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_CONN_INFRA_SLP_COUNTER_STOP_SHFT 7
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_BTSYS_SLP_COUNTER_STOP_ADDR CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_ADDR
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_BTSYS_SLP_COUNTER_STOP_MASK 0x00000004                // HOST_BTSYS_SLP_COUNTER_STOP[2]
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_BTSYS_SLP_COUNTER_STOP_SHFT 2
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_WFSYS_SLP_COUNTER_STOP_ADDR CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_ADDR
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_WFSYS_SLP_COUNTER_STOP_MASK 0x00000002                // HOST_WFSYS_SLP_COUNTER_STOP[1]
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_WFSYS_SLP_COUNTER_STOP_SHFT 1
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_GPSSYS_SLP_COUNTER_STOP_ADDR CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_ADDR
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_GPSSYS_SLP_COUNTER_STOP_MASK 0x00000001                // HOST_GPSSYS_SLP_COUNTER_STOP[0]
#define CONN_HOST_CSR_TOP_HOST_CONN_INFRA_SLP_CNT_SLP_STOP_HOST_GPSSYS_SLP_COUNTER_STOP_SHFT 0

#endif // __CONN_HOST_CSR_TOP_REGS_H__
