#obj-$(CONFIG_OPLUS_COMMON_SOFT)  +=  oplus_project/
#obj-$(CONFIG_OPLUS_DEVICE_IFNO)  +=  oplus_devinfo/
obj-y += oplus_criticallog/
#obj-y += oplus_custom/
#obj-$(CONFIG_OPLUS_HYPNUS)       +=  oplus_hypnus/

#Liang.Zhang@TECH.Storage.Stability.OPLUS_SHUTDOWN_DETECT, 2019/04/28, Add for shutdown detect
#obj-$(CONFIG_OPLUS_SHUTDOWN_DETECT)  +=  oplus_shutdown_detect/
#obj-$(CONFIG_OPLUS_CRITICALLOG)  +=  oplus_criticallog/
#obj-y  +=  oplus_criticallog/

#Kun.Hu@TECH.BSP.Stability.PHOENIX_PROJECT 2019/06/15, Add for PHOENIX_PROJECT
#obj-$(CONFIG_OPLUS_PHOENIX)     +=  oplus_phoenix/

#obj-$(CONFIG_OPLUS_KEY_HANDLE)    +=  oplus_key_handle/

#ifdef OPLUS_FEATURE_NFC_CONSOFT
#obj-$(CONFIG_OPLUS_NFC)     +=  oplus_nfc/
#endif /* OPLUS_FEATURE_NFC_CONSOFT */

#ifdef OPLUS_FEATURE_SENSOR_SMEM
#obj-$(CONFIG_OPLUS_ALS_CALI)   +=  oplus_als_cali_value/
#endif /*OPLUS_FEATURE_SENSOR_SMEM */

#ifdef OPLUS_FEATURE_MEMLEAK_DETECT
#Hailong.Liu@BSP.MM 2019/03/18, Add for svelte
#obj-$(CONFIG_OPLUS_SVELTE)     +=  oplus_svelte/
#endifi /* OPLUS_FEATURE_MEMLEAK_DETECT */

#obj-$(CONFIG_OPLUS_WAKELOCK_PROFILER)     +=  oplus_wakelock_profiler/

