# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

obj-y += uifirst_sched_common.o
obj-y += uifirst_sched_mutex.o
obj-y += uifirst_sched_rwsem.o
obj-y += uifirst_sched_futex.o
obj-y += uifirst_sched_workqueue.o

